version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/docker-prueba/pagina/html/
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Prueba1
volumes:
  db-data:
